<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Smoke Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>387d6621-8c65-4abb-82f7-3455da7c702e</testSuiteGuid>
   <testCaseLink>
      <guid>f9b8aa5c-e0d4-42a1-b351-8153d6923df4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smoke Test/TC1_NewCall</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39b454ae-95ad-421f-95f0-1b84898ae608</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b3a690e-016b-4dc2-9daa-a970fe34d570</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79d4b42e-f34f-40a8-a38d-33d679da1355</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68744764-813f-49ac-bb18-f010e51e442f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6cd2dcda-6376-45a3-baa6-9ad717fb81f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smoke Test/TC2_EmergencyCall</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2155059-0754-4eed-9da7-140fbd027ca2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ab31744-6789-4527-93c1-b75b2c6a4e54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smoke Test/TC3_CompleteExistingTrip</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a43701d3-94d9-42c8-a8e1-8a90a881235f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2e751e28-8d98-409c-a7ce-cb0274f34bd4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smoke Test/TC4_UnitActivation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a59968d-bd67-4ed4-9b8d-cd09c0f0c3cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e280742d-d4f3-4655-a5e8-ea74839140f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d898863-3eb3-4295-a6ff-5098731c60ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd538945-58af-4df7-8518-f41df968edcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17c5755d-0bbe-4269-a53f-c9b54f81ebc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37cf044d-5759-477c-9fdf-b36e007c76ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7e0745b-39d6-4024-bc92-64a548ba8716</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smoke Test/TC5_ValidateClaim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2336d5fc-4e86-4c15-857b-9b5e885ca727</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f91476d6-c3e9-4b0d-8ac9-8b9c7c60c101</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>823df075-0994-471a-9e4f-b0bee3700dd6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smoke Test/TC6_AddNewPatient</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1bcf099-85c6-4a26-b004-5bb3aeff3174</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d6c10e6-037d-4845-a6c9-6062f74bbca2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85960eca-722b-4d35-88f2-802800257f0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5abbcc7f-f02f-473d-b4ba-c06b40a73dd9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50b07a25-8e93-40f5-b712-3dfcad6372b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c58175d8-8477-41b3-ace2-8b1b6773b398</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smoke Test/TC7_CreateNewValidClaim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c03b29b5-76ed-43a9-baad-df2d0831f70e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaad82cf-d2e3-4d77-91b1-128a39a8278b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2653729-ea12-47ae-885e-1eb7b7466220</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c06dc19-2d2e-4b49-bc8b-54902756d192</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>619adb1b-5838-4bcd-8121-e27333ec298f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18f407a3-308d-4e91-a04f-7df54af8b281</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5961fd7c-ae3b-43bc-92da-311c585e4d11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e95454dc-25bf-4688-8361-042559f1fa03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96ba2c14-dadf-446d-a8b2-9c71ebb8d3df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b82c6b5-5488-43b0-8da2-23805cea1937</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5b44ff0-9489-4c57-88b5-bf8069e9cb13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18697c4e-e26b-4ee3-a384-d752587b7ae7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f85d8d9e-cf54-4b91-9155-3fdbea7de494</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb74403f-18e5-44d7-9621-143757efb405</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e41bfb0-3258-440a-b25d-c7bbc14ada3e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc128b80-fc91-494e-a65a-80d7387ed998</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Smoke Test/TC8_NEMSIS_FileImport</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
