<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_patientByName</name>
   <tag></tag>
   <elementGuidId>565dad93-34b1-48b0-955d-7b2ec0405a87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//dd[text()='${patient}'])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
